'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const supabase=createClient('https://vgtscbpznpopiehjuike.supabase.co','sb_publishable_NN8dZv3f2yTimgiRB8oiHQ_wrTUq7c2');
function miles(a,b){if(!a||!b)return null;const R=3958.8,p=Math.PI/180,dlat=(b.latitude-a.latitude)*p,dlon=(b.longitude-a.longitude)*p,x=Math.sin(dlat/2)**2+Math.cos(a.latitude*p)*Math.cos(b.latitude*p)*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
export default function Home(){const [user,setUser]=useState(null),[me,setMe]=useState(null),[members,setMembers]=useState([]),[name,setName]=useState('Sean'),[status,setStatus]=useState('Connecting…'),[sharing,setSharing]=useState(true),[selected,setSelected]=useState(null);
useEffect(()=>{(async()=>{let {data:{session}}=await supabase.auth.getSession();if(!session){const r=await supabase.auth.signInAnonymously();session=r.data.session;if(r.error){setStatus('Family sign-in needs enabling');return}}setUser(session.user)})()},[]);
useEffect(()=>{if(!user)return;let watch;if(sharing&&navigator.geolocation)watch=navigator.geolocation.watchPosition(async p=>{const x={id:user.id,display_name:name,latitude:p.coords.latitude,longitude:p.coords.longitude,speed_mph:Math.max(0,(p.coords.speed||0)*2.23694),sharing:true,updated_at:new Date().toISOString()};setMe(x);setStatus('Sharing location');await supabase.from('family_locations').upsert(x)},()=>setStatus('Allow precise location'),{enableHighAccuracy:true,maximumAge:5000,timeout:15000});else setStatus('Sharing paused');
const load=async()=>{const {data}=await supabase.from('family_locations').select('*').eq('sharing',true);if(data){setMembers(data);if(!selected&&data[0])setSelected(data[0].id)}};load();const ch=supabase.channel('family-live').on('postgres_changes',{event:'*',schema:'public',table:'family_locations'},load).subscribe();return()=>{if(watch)navigator.geolocation.clearWatch(watch);supabase.removeChannel(ch)}},[user,sharing,name]);
async function toggle(){if(sharing&&user)await supabase.from('family_locations').update({sharing:false,updated_at:new Date().toISOString()}).eq('id',user.id);setSharing(v=>!v)}
const s=members.find(x=>x.id===selected)||me||members[0],dist=useMemo(()=>me&&s?miles(me,s):null,[me,s]);
return <main><header><div><b>Henson Family</b><small>{status}</small></div><button className="share" onClick={toggle}>{sharing?'Sharing ON':'Sharing OFF'}</button></header><section className="map"><div className="roads">＋</div>{members.map((m,i)=><button key={m.id} onClick={()=>setSelected(m.id)} className={'pin p'+(i%2)}>{(m.display_name||'?')[0]}</button>)}<div className="maplabel">LIVE FAMILY MAP</div></section><section className="sheet"><div className="handle"/>{s?<><h2>{s.display_name}</h2><div className="stats"><div><strong>{dist===null?'—':dist.toFixed(1)}</strong><span>miles away</span></div><div><strong>{Math.round(s.speed_mph||0)}</strong><span>mph</span></div><div><strong>{dist&&s.speed_mph>2?Math.max(1,Math.round(dist/s.speed_mph*60)):'—'}</strong><span>min ETA</span></div></div><div className="address"><b>{s.speed_mph>2?'Driving':'Stopped'}</b><p>Live GPS location</p><small>Updated {new Date(s.updated_at).toLocaleTimeString()}</small></div></>:<div className="address"><b>Waiting for family location</b><p>Grant location permission to start sharing.</p></div>}<h3>Family</h3>{members.map(m=><button className="member" key={m.id} onClick={()=>setSelected(m.id)}><i>{(m.display_name||'?')[0]}</i><span><b>{m.display_name}</b><small>{m.speed_mph>2?'Driving · '+Math.round(m.speed_mph)+' mph':'Stopped'}</small></span><em>›</em></button>)}<p className="privacy">Location sharing is visible and voluntary. Each family member must join and grant location permission.</p></section></main>}